### ISSUE TITLE
Chrome is flickering and is failing to start - logs included [MacOS]

### ISSUE THREAD

**Issue by comanbo** [stefanjenkner/payback-activate#4]
> wdio
> wdio run ./wdio.conf.js

Execution of 1 workers started at 2023-05-14T20:30:01.165Z

2023-05-14T20:30:01.236Z INFO chromedriver: Initiate Chromedriver Launcher (v8.1.1)
2023-05-14T20:30:01.238Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-05-14T20:30:01.241Z INFO chromedriver: Start Chromedriver (/Users/bogdan/Desktop/payback-activate-main/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2023-05-14T20:30:01.265Z INFO chromedriver: Starting ChromeDriver 111.0.5563.64 (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}) on port 9515
2023-05-14T20:30:01.265Z INFO chromedriver: Only local connections are allowed.
2023-05-14T20:30:01.265Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-05-14T20:30:01.270Z INFO chromedriver: ChromeDriver was started successfully.
2023-05-14T20:30:01.359Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-05-14T20:30:01.360Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js
[0-0] 2023-05-14T20:30:02.296Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///test/specs/payback.js
[0-0] 2023-05-14T20:30:02.421Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-05-14T20:30:02.547Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-05-14T20:30:02.548Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
**[0-0] 2023-05-14T20:30:04.088Z WARN webdriver: Request failed with status 500 due to session not created: This version of ChromeDriver only supports Chrome version 111**
[0-0] Current browser version is 113.0.5672.92 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[0-0] 2023-05-14T20:30:04.088Z INFO webdriver: Retrying 1/3
[0-0] 2023-05-14T20:30:04.089Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-05-14T20:30:04.089Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] 2023-05-14T20:30:05.196Z WARN webdriver: Request failed with status 500 due to session not created: This version of ChromeDriver only supports Chrome version 111
[0-0] Current browser version is 113.0.5672.92 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[0-0] 2023-05-14T20:30:05.196Z INFO webdriver: Retrying 2/3
[0-0] 2023-05-14T20:30:05.196Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-05-14T20:30:05.196Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] 2023-05-14T20:30:06.302Z WARN webdriver: Request failed with status 500 due to session not created: This version of ChromeDriver only supports Chrome version 111
[0-0] Current browser version is 113.0.5672.92 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[0-0] 2023-05-14T20:30:06.302Z INFO webdriver: Retrying 3/3
[0-0] 2023-05-14T20:30:06.302Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-05-14T20:30:06.302Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] 2023-05-14T20:30:07.458Z ERROR webdriver: Request failed with status 500 due to session not created: session not created: This version of ChromeDriver only supports Chrome version 111
[0-0] Current browser version is 113.0.5672.92 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[0-0] 2023-05-14T20:30:07.458Z ERROR webdriver: session not created: session not created: This version of ChromeDriver only supports Chrome version 111
[0-0] Current browser version is 113.0.5672.92 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[0-0]     at getErrorFromResponseBody (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/utils.js:194:12)
[0-0]     at NodeJSRequest._request (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/request/index.js:164:23)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async startWebDriverSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/utils.js:63:20)
[0-0]     at async WebDriver.newSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/index.js:24:45)
[0-0]     at async remote (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriverio/build/index.js:48:22)
[0-0]     at async Runner._startSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner._initSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:187:25)
[0-0]     at async Runner.run (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:77:19)
[0-0] 2023-05-14T20:30:07.458Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] session not created: This version of ChromeDriver only supports Chrome version 111
[0-0] Current browser version is 113.0.5672.92 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[0-0]     at startWebDriverSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/utils.js:68:15)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async WebDriver.newSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/index.js:24:45)
[0-0]     at async remote (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriverio/build/index.js:48:22)
[0-0]     at async Runner._startSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner._initSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:187:25)
[0-0]     at async Runner.run (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:77:19)
[0-0] FAILED in chrome - file:///test/specs/payback.js
2023-05-14T20:30:07.576Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-05-14T20:30:07.576Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:06 

2023-05-14T20:30:07.578Z INFO @wdio/local-runner: Shutting down spawned worker
2023-05-14T20:30:07.832Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-05-14T20:30:07.832Z INFO @wdio/local-runner: shutting down

**Comment by stefanjenkner** [comment]
Thanks for bringing this up, @comanbo - should be fixed in `main` branch now! Feel free to give it a try.

**Comment by comanbo** [comment]
still no luck

`
> wdio
> wdio run ./wdio.conf.js


Execution of 1 workers started at 2023-05-21T21:09:38.612Z

2023-05-21T21:09:38.679Z INFO chromedriver: Initiate Chromedriver Launcher (v8.1.1)
2023-05-21T21:09:38.681Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-05-21T21:09:38.683Z INFO chromedriver: Start Chromedriver (/Users/bogdan/Desktop/payback-activate-main/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2023-05-21T21:09:38.707Z INFO chromedriver: Starting ChromeDriver 111.0.5563.64 (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}) on port 9515
2023-05-21T21:09:38.708Z INFO chromedriver: Only local connections are allowed.
2023-05-21T21:09:38.708Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-05-21T21:09:38.712Z INFO chromedriver: ChromeDriver was started successfully.
2023-05-21T21:09:38.798Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-05-21T21:09:38.799Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js
[0-0] 2023-05-21T21:09:39.716Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///test/specs/payback.js
[0-0] 2023-05-21T21:09:39.844Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-05-21T21:09:39.977Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-05-21T21:09:39.977Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] 2023-05-21T21:09:40.010Z WARN webdriver: Request failed with status 500 due to unknown error: cannot find Chrome binary
[0-0] 2023-05-21T21:09:40.011Z INFO webdriver: Retrying 1/3
[0-0] 2023-05-21T21:09:40.011Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-05-21T21:09:40.011Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] 2023-05-21T21:09:40.017Z WARN webdriver: Request failed with status 500 due to unknown error: cannot find Chrome binary
[0-0] 2023-05-21T21:09:40.017Z INFO webdriver: Retrying 2/3
[0-0] 2023-05-21T21:09:40.017Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-05-21T21:09:40.017Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] 2023-05-21T21:09:40.022Z WARN webdriver: Request failed with status 500 due to unknown error: cannot find Chrome binary
[0-0] 2023-05-21T21:09:40.022Z INFO webdriver: Retrying 3/3
[0-0] 2023-05-21T21:09:40.022Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-05-21T21:09:40.022Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] 2023-05-21T21:09:40.026Z ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: cannot find Chrome binary
[0-0] 2023-05-21T21:09:40.027Z ERROR webdriver: unknown error: unknown error: cannot find Chrome binary
[0-0]     at getErrorFromResponseBody (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/utils.js:194:12)
[0-0]     at NodeJSRequest._request (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/request/index.js:164:23)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async startWebDriverSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/utils.js:63:20)
[0-0]     at async WebDriver.newSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/index.js:24:45)
[0-0]     at async remote (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriverio/build/index.js:48:22)
[0-0]     at async Runner._startSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner._initSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:187:25)
[0-0]     at async Runner.run (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:77:19)
[0-0] 2023-05-21T21:09:40.027Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] unknown error: cannot find Chrome binary
[0-0]     at startWebDriverSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/utils.js:68:15)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async WebDriver.newSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriver/build/index.js:24:45)
[0-0]     at async remote (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/webdriverio/build/index.js:48:22)
[0-0]     at async Runner._startSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner._initSession (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:187:25)
[0-0]     at async Runner.run (file:///Users/bogdan/Desktop/payback-activate-main/node_modules/@wdio/runner/build/index.js:77:19)
[0-0] FAILED in chrome - file:///test/specs/payback.js
2023-05-21T21:09:40.144Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-05-21T21:09:40.145Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:01 

2023-05-21T21:09:40.147Z INFO @wdio/local-runner: Shutting down spawned worker
2023-05-21T21:09:40.398Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-05-21T21:09:40.398Z INFO @wdio/local-runner: shutting down`

**Comment by stefanjenkner** [comment]
@comanbo Sorry to hear that. Please note that Google Chrome is currently required to run the script. Based on the logs you've shared, it looks like `chromedriver` cannot find the Google Chrome binary.  I suggest to check the [the requirements here](https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver/01fde32d0ed245141e24151f83b7c2db31d596a4#requirements) to verify that the binary is located at the expected location. I hope this helps.
